apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
        - name: lms
          image: husseinsahm/lms:latest
          ports:
            - containerPort: 5000

          # هنا تخزين قاعدة البيانات
          volumeMounts:
            - name: lms-db
              mountPath: /app/data  # مجلد يحتوي db
          
      volumes:
        - name: lms-db
          persistentVolumeClaim:
            claimName: lms-pvc
